---

- name: create dir
  file: path=/nfs/general/ state=directory owner={{nfs_user}}

- name: mount NFS directory
  shell: mount {{ hostvars[groups[cluster_name + '_master'][0]].openstack.public_v4 }}:/var/nfs/general /nfs/general
  become: true
  become_user: root

#- name: crate mount point
#  lineinfile:
#    dest=/etc/fstab
#    state=present insertafter=EOF
#    line="{{ hostvars[groups[cluster_name + '_master'][0]].openstack.public_v4 }}  {{item.mount_path}}       nfs    owner={{nfs_user}}        0       2"
#    create=true
