---

- name: update apt cache
  apt: update_cache=yes

- name: install packages
  apt: name={{ item }} state=present
  with_items:
    - nfs-kernel-server
    - nfs-common
  tags:
  - prepare


- include: add_share.yml
  with_items: "{{nfs_shares}}"
  tags:
  - prepare

- name: create dir for mounting at clients
  file: path=/nfs/general/ state=directory owner={{nfs_user}}

- name: create dir to be shared
  file: path=/var/nfs/general/ state=directory owner={{nfs_user}}


- name: specify dir to be shared in exports
  lineinfile:
      dest=/etc/exports
      state=present insertafter=EOF
      line="/var/nfs/general    {{ hostvars[groups[item][0]].openstack.private_v4 }}(rw,sync,no_subtree_check)"
      create=true
  with_sequence: start=1 end={{ n_slaves }} format={{ cluster_name }}-slave-%d

- name: specify mount point in fstab
  lineinfile:
    dest=/etc/fstab
    state=present insertafter=EOF
    line="{{ hostvars[groups[cluster_name + '_master'][0]].openstack.public_v4 }}:/var/nfs/general    /nfs/general   nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0"
    create=true

- name: Restart NFS
  service: "name=nfs-kernel-server state=restarted"

- name: mount NFS dir in clients
  shell: mount {{ hostvars[groups[cluster_name + '_master'][0]].openstack.private_v4 }}:/var/nfs/general /nfs/general
  become: true
  become_user: root
  ignore_errors: yes #For master node
  tags:
    - prepare
